import type { OmarchyTheme, SemanticOmarchyTokens } from './theme.js';

export function toCssVariables(tokens: SemanticOmarchyTokens, selector = ':root'): string {
  const lines = Object.entries(tokens).map(([key, value]) => `  --omarchy-${kebab(key)}: ${value};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

export function toJsonTheme(theme: OmarchyTheme): string {
  return `${JSON.stringify(theme, null, 2)}\n`;
}

export function toShellExports(tokens: SemanticOmarchyTokens, prefix = 'OMARCHY'): string {
  const lines = Object.entries(tokens).map(([key, value]) => {
    const name = `${prefix}_${constant(key)}`;
    return `export ${name}=${shellQuote(value)}`;
  });
  return `${lines.join('\n')}\n`;
}

export function toGtkCss(tokens: SemanticOmarchyTokens): string {
  const colorLines = Object.entries(tokens).map(([key, value]) => `@define-color omarchy_${snake(key)} ${value};`);
  const widgetLines = [
    '',
    '* {',
    '  color: @omarchy_foreground;',
    '  background-color: @omarchy_background;',
    '}',
    '',
    'window, popover, menu {',
    '  background-color: @omarchy_background;',
    '  color: @omarchy_foreground;',
    '}',
    '',
    'button, entry, list, row, toolbar, headerbar {',
    '  background-color: @omarchy_surface;',
    '  color: @omarchy_surface_foreground;',
    '  border-color: @omarchy_border;',
    '}',
    '',
    'button:hover, row:hover {',
    '  background-color: @omarchy_surface_raised;',
    '}',
    '',
    'button:focus, entry:focus, row:selected {',
    '  outline-color: @omarchy_accent;',
    '  border-color: @omarchy_accent;',
    '}'
  ];

  return `${colorLines.join('\n')}\n${widgetLines.join('\n')}\n`;
}

export function toDarktableCss(tokens: SemanticOmarchyTokens): string {
  const roleLines = [
    `@define-color omarchy_background ${tokens.background};`,
    `@define-color omarchy_foreground ${tokens.foreground};`,
    `@define-color omarchy_muted_foreground ${tokens.mutedForeground};`,
    `@define-color omarchy_surface ${tokens.surface};`,
    `@define-color omarchy_surface_foreground ${tokens.surfaceForeground};`,
    `@define-color omarchy_surface_raised ${tokens.surfaceRaised};`,
    `@define-color omarchy_surface_raised_foreground ${tokens.surfaceRaisedForeground};`,
    `@define-color omarchy_border ${tokens.border};`,
    `@define-color omarchy_border_strong ${tokens.borderStrong};`,
    `@define-color omarchy_accent ${tokens.accent};`,
    `@define-color omarchy_accent_foreground ${tokens.accentForeground};`,
    `@define-color omarchy_danger ${tokens.danger};`,
    `@define-color omarchy_danger_foreground ${tokens.dangerForeground};`,
    `@define-color omarchy_success ${tokens.success};`,
    `@define-color omarchy_success_foreground ${tokens.successForeground};`,
    `@define-color omarchy_warning ${tokens.warning};`,
    `@define-color omarchy_warning_foreground ${tokens.warningForeground};`,
    `@define-color omarchy_info ${tokens.info};`,
    `@define-color omarchy_info_foreground ${tokens.infoForeground};`,
    '@define-color omarchy_photo_canvas #262626;',
    '@define-color omarchy_photo_canvas_foreground #e6e6e6;',
    '@define-color omarchy_photo_canvas_border #3a3a3a;'
  ];

  const cssLines = [
    '/*',
    ' * Generated by Omarchy Native Kit for darktable.',
    ' *',
    ' * This file maps Omarchy semantic tokens onto darktable/GTK UI chrome while',
    ' * keeping image-review surfaces neutral. Install it manually as an opt-in',
    ' * user theme; the kit never mutates darktable or Omarchy configuration.',
    ' */',
    '',
    ...roleLines,
    '',
    '/* System-native shell: panels, controls, menus, dialogs, and focus. */',
    '* {',
    '  color: @omarchy_foreground;',
    '  background-color: @omarchy_background;',
    '}',
    '',
    'window, dialog, popover, menu, tooltip {',
    '  color: @omarchy_foreground;',
    '  background-color: @omarchy_background;',
    '  border-color: @omarchy_border;',
    '}',
    '',
    '#left, #right, #top, #bottom, notebook, stack, toolbar, headerbar, .dt_module {',
    '  color: @omarchy_surface_foreground;',
    '  background-color: @omarchy_surface;',
    '  border-color: @omarchy_border;',
    '}',
    '',
    'button, entry, combobox, spinbutton, scale, scrollbar, treeview, row {',
    '  color: @omarchy_surface_foreground;',
    '  background-color: @omarchy_surface;',
    '  border-color: @omarchy_border;',
    '}',
    '',
    'button:hover, row:hover, treeview:hover, .dt_module:hover {',
    '  color: @omarchy_surface_raised_foreground;',
    '  background-color: @omarchy_surface_raised;',
    '  border-color: @omarchy_border_strong;',
    '}',
    '',
    'button:checked, row:selected, treeview:selected, tab:checked {',
    '  color: @omarchy_accent_foreground;',
    '  background-color: @omarchy_accent;',
    '  border-color: @omarchy_accent;',
    '}',
    '',
    'button:focus, entry:focus, combobox:focus, spinbutton:focus, scale:focus, row:focus {',
    '  outline-color: @omarchy_accent;',
    '  border-color: @omarchy_accent;',
    '}',
    '',
    '.warning, .dt_warning {',
    '  color: @omarchy_warning_foreground;',
    '  background-color: @omarchy_warning;',
    '}',
    '',
    '.error, .dt_error {',
    '  color: @omarchy_danger_foreground;',
    '  background-color: @omarchy_danger;',
    '}',
    '',
    '.success, .dt_success {',
    '  color: @omarchy_success_foreground;',
    '  background-color: @omarchy_success;',
    '}',
    '',
    '.info, .dt_info {',
    '  color: @omarchy_info_foreground;',
    '  background-color: @omarchy_info;',
    '}',
    '',
    '/* Color-critical workspace: stay neutral around images and previews. */',
    '#center, #preview, #thumbtable, #filmstrip, .dt_view, .dt_image, .dt_preview {',
    '  color: @omarchy_photo_canvas_foreground;',
    '  background-color: @omarchy_photo_canvas;',
    '  border-color: @omarchy_photo_canvas_border;',
    '}'
  ];

  return `${cssLines.join('\n')}\n`;
}

export function toQtPalette(tokens: SemanticOmarchyTokens): string {
  const semanticLines = Object.entries(tokens).map(([key, value]) => `${key}=${value}`);
  const palette = {
    Window: tokens.background,
    WindowText: tokens.foreground,
    Base: tokens.background,
    AlternateBase: tokens.surface,
    ToolTipBase: tokens.surfaceRaised,
    ToolTipText: tokens.surfaceRaisedForeground,
    Text: tokens.foreground,
    Button: tokens.surface,
    ButtonText: tokens.surfaceForeground,
    BrightText: tokens.dangerForeground,
    Link: tokens.info,
    Highlight: tokens.accent,
    HighlightedText: tokens.accentForeground,
    PlaceholderText: tokens.mutedForeground
  };
  const paletteLines = Object.entries(palette).map(([key, value]) => `${key}=${value}`);

  return `[Omarchy]\n${semanticLines.join('\n')}\n\n[QPalette]\n${paletteLines.join('\n')}\n`;
}

function kebab(key: string): string {
  return key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function snake(key: string): string {
  return key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function constant(key: string): string {
  return key.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase();
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
