import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export type ThemeHookOptions = {
  appPath: string;
  cssPath?: string;
  binary?: string;
};

export function toThemeHookScript(options: ThemeHookOptions): string {
  const appPath = resolve(options.appPath);
  const cssPath = resolve(appPath, options.cssPath ?? 'src/omarchy-theme.css');
  const binary = options.binary?.trim() || 'omarchy-native';
  const appName = readPackageName(appPath);

  return [
    '#!/usr/bin/env sh',
    'set -eu',
    '',
    `# Sync Omarchy theme tokens for ${appName}.`,
    '# Generated by Omarchy Native Kit. Review before wiring into Omarchy hooks.',
    `${shellQuote(binary)} theme sync --out ${shellQuote(cssPath)}`,
    ''
  ].join('\n');
}

function readPackageName(appPath: string): string {
  try {
    const packageJson = JSON.parse(readFileSync(join(appPath, 'package.json'), 'utf8')) as { name?: string };
    return packageJson.name || 'omarchy-native-app';
  } catch {
    return 'omarchy-native-app';
  }
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
